<a href="https://colab.research.google.com/github/vedantchauhan/hcd_collection_analysis/blob/master/Updated_Bert_Distilbirt_Roberta_Vedant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
np.random.seed(seed=11)

In [ ]:
## reading excel files
#df1 = pd.read_csv('dataset-IssueComments.csv')
df1 = pd.read_excel("/content/dataset-IssueComments.xlsx")
# test data - added by vc
#df_test = pd.read_excel("/content/data_exploration_all_copy.xlsx")
df_test = pd.read_excel("/content/data_exploration_issues_all_copy.xlsx")

In [ ]:
## renaming columns
df1.rename({'#1: App Usage':'App_Usage', 
                       '#2: Inclusiveness' : 'Inclusiveness', 
                       '#3: User Reaction' : 'User_Reaction', 
                       '#4: Non human-centric' : 'Non_human_centric'},axis = 1, inplace = True)
## renaming columns of test data - added by vc
df_test.rename({'#1: App Usage':'App_Usage', 
                       '#2: Inclusiveness' : 'Inclusiveness', 
                       '#3: User Reaction' : 'User_Reaction', 
                       '#4: Non human-centric' : 'Non_human_centric'},axis = 1, inplace = True)

In [ ]:
## converting columns: float datatype to int
cols=[i for i in df1.columns if i not in ["Content"]]

for col in cols:
    df1[col] = df1[col].astype(int)

In [ ]:
## dropping last row: contained the sum of columns
df1.drop(df1.tail(1).index,inplace=True)

In [ ]:
labels = df1[["App_Usage", "Inclusiveness", "User_Reaction", "Non_human_centric"]]
y = labels.values
print(y)
df1['tags'] = list(y)

print(df1)

[[0 0 0 1]
 [0 0 0 1]
 [1 1 0 0]
 ...
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]]
                                                Content  App_Usage  \
0     You are right @Hauwertlhaufn!\nIt is the same ...          0   
1     @moving-bits , @MagpieFourtyTwo Thanks for the...          0   
2     Maybe we should place some often used shortcut...          1   
3     WFM.\nIs it possible that the line break depen...          0   
4     We can work together on this. I want to learn ...          0   
...                                                 ...        ...   
1195  The linked issue isn't outdated and clearly sh...          0   
1196  Hm, can't this behavior be easily achieved by ...          1   
1197  The 'thread spanning multiple folders' thing i...          0   
1198  That sounds more like a problem with your devi...          0   
1199  better wait for word from @cketti if we want t...          0   

      Inclusiveness  User_Reaction  Non_human_centric          tags  
0                

In [ ]:
# added by vc
labels = df_test[["App_Usage", "Inclusiveness", "User_Reaction", "Non_human_centric"]]
y_df_test = labels.values
print(y_df_test)
df_test['tags'] = list(y_df_test)

print(df_test)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
                                                Content  App_Usage  \
0                                                     -          0   
1     Sorry I didn't see the topic like ''Social Imp...          0   
2                                                     -          0   
3             Adding ALBEF to Multimodal Pre-Training.           0   
4                                                     -          0   
...                                                 ...        ...   
1146  https://github.com/afc163/surge-preview/issues/62          0   
1147  #### Mand Mobile Version\r\n2.4.1            \...          0   
1148  ### What problem does this feature solve?\r\n\...          0   
1149   <a href="https://mand-mobile.github.io/mand-m...          0   
1150  \r\n\r\n\u8fd9\u6837 fork \u4ed3\u5e93\u4e5f\u...          0   

      Inclusiveness  User_Reaction  Non_human_centric          tags  
0                

In [ ]:
for i in range(len(df1)):
    df1['tags'][i] = list(map(str, df1['tags'][i]))
    if df1['tags'][i][0]== '1':
        df1['tags'][i][0] = 'App_Usage'
    if df1['tags'][i][1]== '1':
        df1['tags'][i][1] = 'Inclusiveness'
    if df1['tags'][i][2]== '1':
        df1['tags'][i][2] = 'User_Reaction'
    if df1['tags'][i][3]== '1':
        df1['tags'][i][3] = 'Non_human_centric'
    df1['tags'][i] = [j for j in df1['tags'][i] if j != '0']

print(df1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()


                                                Content  App_Usage  \
0     You are right @Hauwertlhaufn!\nIt is the same ...          0   
1     @moving-bits , @MagpieFourtyTwo Thanks for the...          0   
2     Maybe we should place some often used shortcut...          1   
3     WFM.\nIs it possible that the line break depen...          0   
4     We can work together on this. I want to learn ...          0   
...                                                 ...        ...   
1195  The linked issue isn't outdated and clearly sh...          0   
1196  Hm, can't this behavior be easily achieved by ...          1   
1197  The 'thread spanning multiple folders' thing i...          0   
1198  That sounds more like a problem with your devi...          0   
1199  better wait for word from @cketti if we want t...          0   

      Inclusiveness  User_Reaction  Non_human_centric  \
0                 0              0                  1   
1                 0              0           

In [ ]:
##############################################################################################################################

In [ ]:
##REFERENCE: https://github.com/pnageshkar/NLP/blob/master/Medium/Multi_label_Classification_BERT_Lightning.ipynb

In [ ]:
! pip install -q pytorch-lightning
! pip install -q bs4
! pip install -q transformers

     |████████████████████████████████| 798 kB 38.4 MB/s 
     |████████████████████████████████| 529 kB 63.1 MB/s 
     |████████████████████████████████| 87 kB 6.1 MB/s 
     |████████████████████████████████| 5.5 MB 37.4 MB/s 
     |████████████████████████████████| 163 kB 70.6 MB/s 
     |████████████████████████████████| 7.6 MB 57.2 MB/s 


In [ ]:
import pytorch_lightning as pl
from pytorch_lightning.callbacks import ModelCheckpoint

In [ ]:
# Import all libraries
import pandas as pd
import numpy as np
import re

# Huggingface transformers
import transformers
from transformers import BertModel,BertTokenizer,AdamW, get_linear_schedule_with_warmup
from transformers import RobertaTokenizer, DistilBertTokenizer

import torch
from torch import nn ,cuda
from torch.utils.data import DataLoader,Dataset,RandomSampler, SequentialSampler


from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

#handling html data
from bs4 import BeautifulSoup

import seaborn as sns
from pylab import rcParams
import matplotlib.pyplot as plt
from matplotlib import rc
%matplotlib inline

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [ ]:
torch.cuda.empty_cache()

In [ ]:
def pre_process(text):

  text = BeautifulSoup(str(text)).get_text()
  
  # fetch alphabetic characters
  text = re.sub("[^a-zA-Z]", " ", text)

  # convert text to lower case
  text = text.lower()

  # split text into tokens to remove whitespaces
  tokens = text.split()

  return " ".join(tokens)

In [ ]:
# clean the text in Body column
df1['Clean_Content'] = df1['Content'].apply(pre_process)
print(df1)

                                                Content  App_Usage  \
0     You are right @Hauwertlhaufn!\nIt is the same ...          0   
1     @moving-bits , @MagpieFourtyTwo Thanks for the...          0   
2     Maybe we should place some often used shortcut...          1   
3     WFM.\nIs it possible that the line break depen...          0   
4     We can work together on this. I want to learn ...          0   
...                                                 ...        ...   
1195  The linked issue isn't outdated and clearly sh...          0   
1196  Hm, can't this behavior be easily achieved by ...          1   
1197  The 'thread spanning multiple folders' thing i...          0   
1198  That sounds more like a problem with your devi...          0   
1199  better wait for word from @cketti if we want t...          0   

      Inclusiveness  User_Reaction  Non_human_centric  \
0                 0              0                  1   
1                 0              0           

In [ ]:
# clean the text in Body column - added by vc
df_test['Clean_Content'] = df_test['Content'].apply(pre_process)
print(df_test)

/usr/local/lib/python3.7/dist-packages/bs4/__init__.py:336: UserWarning: "https://github.com/GroupeMINASTE/BaseConverter-iOS" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup
/usr/local/lib/python3.7/dist-packages/bs4/__init__.py:336: UserWarning: "https://www.atrinh.com/covid/index.html\r\n\r\nhttps://github.com/atrinh0/covid19\r\n\r\n![](https://github.com/atrinh0/covid19/blob/master/images/graphs.png?raw=true)" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup
/usr/local/lib/python3.7/dist-packages/bs4/__init__.py:336: UserWarning: "https://github.com/vernemq/vernemq/issues/1928" looks like a URL. Beautif

                                                Content  App_Usage  \
0                                                     -          0   
1     Sorry I didn't see the topic like ''Social Imp...          0   
2                                                     -          0   
3             Adding ALBEF to Multimodal Pre-Training.           0   
4                                                     -          0   
...                                                 ...        ...   
1146  https://github.com/afc163/surge-preview/issues/62          0   
1147  #### Mand Mobile Version\r\n2.4.1            \...          0   
1148  ### What problem does this feature solve?\r\n\...          0   
1149   <a href="https://mand-mobile.github.io/mand-m...          0   
1150  \r\n\r\n\u8fd9\u6837 fork \u4ed3\u5e93\u4e5f\u...          0   

      Inclusiveness  User_Reaction  Non_human_centric          tags  \
0                 0              0                  0  [0, 0, 0, 0]   
1                

/usr/local/lib/python3.7/dist-packages/bs4/__init__.py:336: UserWarning: "https://github.com/afc163/surge-preview/issues/62" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup


In [ ]:
x = df1['Clean_Content'].to_list()
print(x)
y = df1['tags'].to_list()
print(y)

['you are right hauwertlhaufn it is the same behavior in facebook imdb and spotify app s search functions as well very strange behavior imho but it still should return to the default action bar instead of the one above without the c geo title and history icon', 'moving bits magpiefourtytwo thanks for the good insights i did not think before about situations where filtering has to be done on transient lists not stored in db like results from address searches i agree with moving bits that this should be tackled at a larger context rework of searching displaying and filtering of cache lists and he describes the situation perfectly this is however a larger topic i am interested in tackling this but i won t be able to do this right now hence my suggestion i will create a pr speeding up in memory filtering based on my findings yesterday because this is simply not programmed in a performant way currently this should already increase dramatically the current problems of magpiefourtytwo describ

In [ ]:
#converting df test data into list - added by vc

x_df_test = df_test['Clean_Content'].to_list()
print(x_df_test)
y_df_test = df_test['tags'].to_list()
print(y_df_test)

['', 'sorry i didn t see the topic like social impact u fairness and misinformation but i saw this topic in your course thank you', '', 'adding albef to multimodal pre training', '', '', 'learning with noisy correspondence for cross modal matching neurips', '', '', 'add new multimodal work accepted by ijcai', '', '', 'add a paper to the category of analysis of multimodal models', 'add one paper under vqa r n add one workshop', 'hey pliang r n i ve updated the url to the recent jair published version', 'hi r nhow do you access the courses mentioned any online courses on multimodal ml', 'nan', 'thank you for your contribution to multimodal research', 'nan', 'nan', 'hi r n r nthis is a preprint recently published by researchers at fair transformer is all you need multimodal multitask learning with a unified transformer https arxiv org abs r n r nadditionally i was wondering about adding paper summaries for these papers in the list so it is easier to use for everyone else a summary readme 

In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
 
yt = mlb.fit_transform(y)
yt.shape

(1200, 4)

In [ ]:
print(yt)

[[0 0 1 0]
 [0 0 1 0]
 [1 1 0 0]
 ...
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]]


In [ ]:
# compute no. of words in each question
questions = x
word_cnt = [len(quest.split()) for quest in questions]
print(word_cnt)

[47, 193, 48, 44, 95, 6, 11, 159, 19, 44, 12, 43, 159, 36, 27, 26, 9, 53, 44, 8, 40, 41, 112, 20, 23, 25, 8, 43, 56, 23, 21, 10, 97, 14, 188, 5, 41, 53, 15, 13, 42, 46, 38, 7, 37, 39, 14, 130, 60, 118, 54, 75, 10, 72, 34, 17, 46, 83, 62, 20, 40, 31, 67, 55, 56, 20, 112, 6, 88, 83, 33, 79, 55, 21, 39, 12, 58, 13, 24, 16, 36, 167, 171, 57, 12, 110, 23, 28, 29, 30, 44, 15, 21, 68, 40, 27, 28, 20, 21, 86, 1, 43, 45, 106, 157, 42, 13, 15, 8, 81, 55, 72, 8, 97, 110, 113, 20, 51, 55, 22, 6, 47, 123, 11, 37, 15, 104, 62, 6, 7, 145, 60, 22, 19, 7, 41, 267, 15, 40, 6, 96, 41, 22, 24, 7, 57, 43, 8, 157, 75, 34, 10, 77, 28, 96, 250, 13, 26, 203, 25, 68, 101, 73, 12, 32, 9, 13, 503, 99, 16, 20, 22, 24, 11, 29, 160, 945, 12, 29, 44, 7, 13, 34, 10, 11, 24, 27, 24, 47, 9, 82, 47, 44, 67, 34, 397, 18, 7, 22, 242, 20, 10, 73, 7, 66, 46, 6, 18, 6, 24, 42, 27, 25, 194, 50, 29, 19, 315, 7, 281, 5, 53, 11, 31, 14, 59, 85, 11, 105, 56, 59, 58, 14, 26, 57, 16, 35, 183, 17, 31, 112, 168, 58, 19, 60, 17, 150, 2

In [ ]:
# compute no. of words in each question - added by vc
questions_test = x_df_test
word_cnt_test = [len(quest.split()) for quest in questions_test]
print(word_cnt_test)

[0, 24, 0, 6, 0, 0, 9, 0, 0, 7, 0, 0, 11, 10, 15, 15, 1, 8, 1, 1, 102, 15, 109, 10, 1, 1, 6, 20, 92, 1, 11, 48, 1, 1, 1, 1, 1, 1, 13, 1, 1, 17, 1, 44, 14, 1, 19, 1, 2, 1, 1, 100, 30, 11, 9, 30, 57, 7, 51, 134, 9, 24, 181, 4, 30, 124, 30, 91, 35, 162, 21, 40, 90, 67, 136, 28, 66, 151, 160, 195, 113, 289, 42, 30, 15, 721, 55, 230, 65, 49, 172, 1, 30, 225, 115, 78, 626, 68, 72, 46, 66, 144, 114, 165, 9, 131, 55, 3, 225, 10, 35, 67, 10, 75, 108, 75, 38, 110, 102, 53, 30, 75, 71, 82, 2, 5, 4, 5, 237, 120, 1, 118, 85, 47, 60, 58, 127, 62, 165, 167, 320, 44, 30, 27, 30, 30, 274, 4, 5, 53, 5, 138, 149, 226, 49, 236, 574, 35, 550, 34, 12, 265, 38, 736, 43, 79, 0, 244, 7, 561, 35, 16, 338, 28, 36, 24, 67, 25, 706, 35, 19, 38, 56, 21, 148, 77, 89, 209, 920, 34, 34, 76, 63, 0, 29, 49, 17, 9, 69, 38, 10, 35, 105, 20, 379, 196, 7, 221, 36, 43, 68, 62, 24, 535, 123, 725, 336, 15, 79, 128, 476, 97, 7, 1493, 53, 92, 13, 151, 328, 2716, 316, 378, 52, 264, 148, 43, 15, 30, 15, 41, 53, 41, 553, 580, 89, 7

In [ ]:
from sklearn.model_selection import train_test_split
# First Split for Train and Test
x_train,x_test,y_train,y_test = train_test_split(x, yt, test_size=0.1, random_state=RANDOM_SEED,shuffle=True)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

#TODO - change the test data set to vc one

# Next split Train in to training and validation
x_tr,x_val,y_tr,y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=RANDOM_SEED,shuffle=True)

['damn rmeq is your own script i m sorry d', 'it was never my intention to integrate the translation into pixel dungeon but rather publishing it as a separate application i already started with the translation in my project german pixel dungeon as already arranged with evan debenham i also plan to translate shattered pixel dungeon when i am ready with translating pixel dungeon i will be glad about anybody helping me because i am still going to school for years and i just started to study it at the university i have not so much time to work on the translation but i d like to finish it within the next months furthermore i will be glad about someone corrects my translation ich habe eigentlich nie vorgehabt die bersetzung in pixel dungeon zu integrieren sondern wollte es als eigenst ndige app ver ffentlichen mit der bersetzung habe ich bereits in meinem projekt german pixel dungeon angefangen und wie schon mit evan debenham abgesprochen habe ich vor auch shattered pixel dungeon zu bersetze

In [ ]:
class QTagDataset (Dataset):
    def __init__(self,quest,tags, tokenizer, max_len):
        self.tokenizer = tokenizer
        self.text = quest
        self.labels = tags
        self.max_len = max_len
        
    def __len__(self):
        return len(self.text)
    
    def __getitem__(self, item_idx):
        text = self.text[item_idx]
        inputs = self.tokenizer.encode_plus(
            text,
            None,
            add_special_tokens=True, # Add [CLS] [SEP]
            max_length= self.max_len,
            padding = 'max_length',
            return_token_type_ids= False,
            return_attention_mask= True, # Differentiates padded vs normal token
            truncation=True, # Truncate data beyond max length
            return_tensors = 'pt' # PyTorch Tensor format
          )
        
        input_ids = inputs['input_ids'].flatten()
        attn_mask = inputs['attention_mask'].flatten()
        #token_type_ids = inputs["token_type_ids"]
        
        return {
            'input_ids': input_ids ,
            'attention_mask': attn_mask,
            'label': torch.tensor(self.labels[item_idx], dtype=torch.float)
            
        }

In [ ]:
class QTagDataModule (pl.LightningDataModule):
    
    def __init__(self,x_tr,y_tr,x_val,y_val,x_test,y_test,tokenizer,batch_size=16,max_token_len=200):
        super().__init__()
        self.tr_text = x_tr
        self.tr_label = y_tr
        self.val_text = x_val
        self.val_label = y_val
        self.test_text = x_test
        self.test_label = y_test
        self.tokenizer = tokenizer
        self.batch_size = batch_size
        self.max_token_len = max_token_len

    def setup(self, stage=None):
        self.train_dataset = QTagDataset(quest=self.tr_text, tags=self.tr_label, tokenizer=self.tokenizer,max_len = self.max_token_len)
        self.val_dataset  = QTagDataset(quest=self.val_text,tags=self.val_label,tokenizer=self.tokenizer,max_len = self.max_token_len)
        self.test_dataset  = QTagDataset(quest=self.test_text,tags=self.test_label,tokenizer=self.tokenizer,max_len = self.max_token_len)
        
        
    def train_dataloader(self):
        return DataLoader (self.train_dataset,batch_size = self.batch_size,shuffle = True , num_workers=2)

    def val_dataloader(self):
        return DataLoader (self.val_dataset,batch_size= 16)

    def test_dataloader(self):
        return DataLoader (self.test_dataset,batch_size= 16)

In [ ]:
# Initialize the Bert tokenizer
BERT_MODEL_NAME = "bert-base-cased" # we will use the BERT base model(the smaller one)
Bert_tokenizer = BertTokenizer.from_pretrained(BERT_MODEL_NAME)

Downloading:   0%|          | 0.00/213k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [ ]:
# Initialize the RoBertA tokenizer
BERT_MODEL_NAME = "roberta-base" # we will use the BERT base model(the smaller one)
Bert_tokenizer = RobertaTokenizer.from_pretrained(BERT_MODEL_NAME)

Downloading:   0%|          | 0.00/899k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/481 [00:00<?, ?B/s]

In [ ]:
# Initialize the DistilBirt tokenizer
BERT_MODEL_NAME = "distilbert-base-uncased" # we will use the BERT base model(the smaller one)
Bert_tokenizer = DistilBertTokenizer.from_pretrained(BERT_MODEL_NAME)

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/483 [00:00<?, ?B/s]

In [ ]:
max_word_cnt = 70
quest_cnt = 0

# For every sentence...
for question in questions:

    # Tokenize the text and add `[CLS]` and `[SEP]` tokens.
    input_ids = Bert_tokenizer.encode(question, add_special_tokens=True)

    # Update the maximum sentence length.
    if len(input_ids) > max_word_cnt:
        quest_cnt +=1

print(f'# Question having word count > {max_word_cnt}: is  {quest_cnt}')

Token indices sequence length is longer than the specified maximum sequence length for this model (541 > 512). Running this sequence through the model will result in indexing errors


# Question having word count > 70: is  301


In [ ]:
# added by vc
max_word_cnt = 70
quest_cnt = 0

# For every sentence...
for question in questions_test:

    # Tokenize the text and add `[CLS]` and `[SEP]` tokens.
    input_ids = Bert_tokenizer.encode(question, add_special_tokens=True)

    # Update the maximum sentence length.
    if len(input_ids) > max_word_cnt:
        quest_cnt +=1

print(f'# Question having word count > {max_word_cnt}: is  {quest_cnt}')

# Question having word count > 70: is  734


In [ ]:
# Initialize the parameters that will be use for training
N_EPOCHS = 5
BATCH_SIZE = 15
#MAX_LEN = 300
# added by vc
MAX_LEN = 512
LR = 2e-05

In [ ]:
# Instantiate and set up the data_module
# changed x_test and y_test to df_test - added by vc
QTdata_module = QTagDataModule(x_tr,y_tr,x_val,y_val,x_df_test,y_df_test,Bert_tokenizer,BATCH_SIZE,MAX_LEN)
QTdata_module.setup()

In [ ]:
class QTagClassifier(pl.LightningModule):
    # Set up the classifier
    def __init__(self, n_classes=4, steps_per_epoch=None, n_epochs=3, lr=2e-5 ):
        super().__init__()

        self.bert = BertModel.from_pretrained(BERT_MODEL_NAME, return_dict=True)
        self.classifier = nn.Linear(self.bert.config.hidden_size,n_classes) # outputs = number of labels
        self.steps_per_epoch = steps_per_epoch
        self.n_epochs = n_epochs
        self.lr = lr
        self.criterion = nn.BCEWithLogitsLoss()
        
    def forward(self,input_ids, attn_mask):
        output = self.bert(input_ids = input_ids ,attention_mask = attn_mask)
        output = self.classifier(output.pooler_output)
                
        return output
    
    
    def training_step(self,batch,batch_idx):
        input_ids = batch['input_ids']
        attention_mask = batch['attention_mask']
        labels = batch['label']
        
        outputs = self(input_ids,attention_mask)
        loss = self.criterion(outputs,labels)
        self.log('train_loss',loss , prog_bar=True,logger=True)
        
        return {"loss" :loss, "predictions":outputs, "labels": labels }


    def validation_step(self,batch,batch_idx):
        input_ids = batch['input_ids']
        attention_mask = batch['attention_mask']
        labels = batch['label']
        
        outputs = self(input_ids,attention_mask)
        loss = self.criterion(outputs,labels)
        self.log('val_loss',loss , prog_bar=True,logger=True)
        
        return loss

    def test_step(self,batch,batch_idx):
        input_ids = batch['input_ids']
        attention_mask = batch['attention_mask']
        labels = batch['label']
        
        outputs = self(input_ids,attention_mask)
        loss = self.criterion(outputs,labels)
        self.log('test_loss',loss , prog_bar=True,logger=True)
        
        return loss
    
    
    def configure_optimizers(self):
        optimizer = AdamW(self.parameters() , lr=self.lr)
        warmup_steps = self.steps_per_epoch//3
        total_steps = self.steps_per_epoch * self.n_epochs - warmup_steps

        scheduler = get_linear_schedule_with_warmup(optimizer,warmup_steps,total_steps)

        return [optimizer], [scheduler]


In [ ]:
# Instantiate the classifier model
steps_per_epoch = len(x_tr)//BATCH_SIZE
model = QTagClassifier(n_classes=4, steps_per_epoch=steps_per_epoch,n_epochs=N_EPOCHS,lr=LR)

You are using a model of type distilbert to instantiate a model of type bert. This is not supported for all configurations of models and can yield errors.


Downloading:   0%|          | 0.00/268M [00:00<?, ?B/s]

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing BertModel: ['distilbert.transformer.layer.1.attention.v_lin.bias', 'distilbert.transformer.layer.1.output_layer_norm.weight', 'distilbert.transformer.layer.4.attention.out_lin.bias', 'distilbert.transformer.layer.5.attention.k_lin.weight', 'distilbert.transformer.layer.0.attention.v_lin.bias', 'distilbert.transformer.layer.5.sa_layer_norm.bias', 'distilbert.transformer.layer.5.sa_layer_norm.weight', 'distilbert.transformer.layer.4.attention.k_lin.bias', 'distilbert.transformer.layer.2.attention.out_lin.weight', 'distilbert.transformer.layer.2.attention.k_lin.weight', 'distilbert.transformer.layer.5.output_layer_norm.weight', 'vocab_transform.weight', 'distilbert.transformer.layer.2.ffn.lin1.bias', 'distilbert.transformer.layer.5.ffn.lin1.bias', 'distilbert.transformer.layer.1.ffn.lin2.bias', 'vocab_layer_norm.weight', 'distilbert.transformer.layer.0.attention.k_lin.weight', 'distilbert.trans

In [ ]:
#Initialize Pytorch Lightning callback for Model checkpointing

# saves a file like: input/QTag-epoch=02-val_loss=0.32.ckpt
checkpoint_callback = ModelCheckpoint(
    monitor='val_loss',# monitored quantity
    filename='QTag-{epoch:02d}-{val_loss:.2f}',
    save_top_k=3, #  save the top 3 models
    mode='min', # mode of the monitored quantity  for optimization
)

In [ ]:
# Instantiate the Model Trainer
#trainer = pl.Trainer(max_epochs = N_EPOCHS, gpus = 1, callbacks=[checkpoint_callback],progress_bar_refresh_rate = 30)
# added by vc - progress_bar_referesh no longer supported
trainer = pl.Trainer(max_epochs = N_EPOCHS, gpus = 1, callbacks=[checkpoint_callback])

# we convert gpus=1 to. gpus = 0

/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:447: LightningDeprecationWarning: Setting `Trainer(gpus=1)` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=1)` instead.
  f"Setting `Trainer(gpus={gpus!r})` is deprecated in v1.7 and will be removed"
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:IPU available: False, using: 0 IPUs
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs


In [ ]:
# Train the Classifier Model
trainer.fit(model, QTdata_module)

INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:310: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,
INFO:pytorch_lightning.callbacks.model_summary:
  | Name       | Type              | Params
-------------------------------------------------
0 | bert       | BertModel         | 109 M 
1 | classifier | Linear            | 3.1 K 
2 | criterion  | BCEWithLogitsLoss | 0     
-------------------------------------------------
109 M     Trainable params
0         Non-trainable params
109 M     Total params
437.941   Total estimated model params size (MB)


Sanity Checking: 0it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=5` reached.


In [ ]:
# Evaluate the model performance on the test dataset
trainer.test(model,datamodule=QTdata_module)

INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Testing: 0it [00:00, ?it/s]

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        test_loss           0.3274822235107422
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


[{'test_loss': 0.3274822235107422}]

In [ ]:
# Retreive the checkpoint path for best model
model_path = checkpoint_callback.best_model_path
model_path



'/content/lightning_logs/version_0/checkpoints/QTag-epoch=03-val_loss=0.36.ckpt'

In [ ]:
# from google.colab import drive
# drive.mount('/content/gdrive')

In [ ]:
from torch.utils.data import TensorDataset

# Tokenize all questions in x_test
input_ids = []
attention_masks = []


for quest in x_df_test:
    encoded_quest =  Bert_tokenizer.encode_plus(
                    quest,
                    None,
                    add_special_tokens=True,
                    max_length= MAX_LEN,
                    padding = 'max_length',
                    return_token_type_ids= False,
                    return_attention_mask= True,
                    truncation=True,
                    return_tensors = 'pt'      
    )
    
    # Add the input_ids from encoded question to the list.    
    input_ids.append(encoded_quest['input_ids'])
    # Add its attention mask 
    attention_masks.append(encoded_quest['attention_mask'])
    
# Now convert the lists into tensors.
input_ids = torch.cat(input_ids, dim=0)
attention_masks = torch.cat(attention_masks, dim=0)
labels = torch.tensor(y_df_test)

# Set the batch size.  
TEST_BATCH_SIZE = 64  

# Create the DataLoader.
pred_data = TensorDataset(input_ids, attention_masks, labels)
pred_sampler = SequentialSampler(pred_data)
pred_dataloader = DataLoader(pred_data, sampler=pred_sampler, batch_size=TEST_BATCH_SIZE)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:29: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)


In [ ]:
flat_pred_outs = 0
flat_true_labels = 0

In [ ]:
# Put model in evaluation mode
model = model.to(device) # moving model to cuda
model.eval()

# Tracking variables 
pred_outs, true_labels = [], []
#i=0
# Predict 
for batch in pred_dataloader:
    # Add batch to GPU
    batch = tuple(t.to(device) for t in batch)
  
    # Unpack the inputs from our dataloader
    b_input_ids, b_attn_mask, b_labels = batch
 
    with torch.no_grad():
        # Forward pass, calculate logit predictions
        pred_out = model(b_input_ids,b_attn_mask)
        pred_out = torch.sigmoid(pred_out)
        # Move predicted output and labels to CPU
        pred_out = pred_out.detach().cpu().numpy()
        label_ids = b_labels.to('cpu').numpy()
        #i+=1
        # Store predictions and true labels
        #print(i)
        #print(outputs)
        #print(logits)
        #print(label_ids)
    pred_outs.append(pred_out)
    true_labels.append(label_ids)

In [ ]:
# Combine the results across all batches. 
flat_pred_outs = np.concatenate(pred_outs, axis=0)
print(flat_pred_outs)

# Combine the correct labels for each batch into a single list.
flat_true_labels = np.concatenate(true_labels, axis=0)
print(flat_true_labels)

[[0.08564158 0.08133035 0.8920753  0.05568031]
 [0.24646594 0.06551924 0.56604916 0.05710638]
 [0.08564158 0.08133035 0.8920753  0.05568031]
 ...
 [0.37589014 0.08924005 0.37361017 0.09129267]
 [0.327824   0.08140526 0.4389566  0.0749777 ]
 [0.3076899  0.07966386 0.4585793  0.07099117]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
# define candidate threshold values
threshold  = np.arange(0.4,0.51,0.01)
threshold

array([0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ])

In [ ]:
# convert probabilities into 0 or 1 based on a threshold value
def classify(pred_prob,thresh):
    y_pred = []

    for tag_label_row in pred_prob:
        temp=[]
        for tag_label in tag_label_row:
            if tag_label >= thresh:
                temp.append(1) # Infer tag value as 1 (present)
            else:
                temp.append(0) # Infer tag value as 0 (absent)
        y_pred.append(temp)

    return y_pred

In [ ]:
from sklearn import metrics
scores=[] # Store the list of f1 scores for prediction on each threshold

#convert labels to 1D array
y_true = flat_true_labels.ravel() 

for thresh in threshold:
    
    #classes for each threshold
    pred_bin_label = classify(flat_pred_outs,thresh) 

    #convert to 1D array
    y_pred = np.array(pred_bin_label).ravel()

    scores.append(metrics.f1_score(y_true,y_pred))

In [ ]:
# find the optimal threshold
opt_thresh = threshold[scores.index(max(scores))]
print(f'Optimal Threshold Value = {opt_thresh}')

Optimal Threshold Value = 0.4


In [ ]:
#predictions for optimal threshold
y_pred_labels = classify(flat_pred_outs,opt_thresh)
y_pred = np.array(y_pred_labels).ravel() # Flatten
print(y_pred_labels)

[[0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 0, 0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 0, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 0, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 0, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 0], [0, 0, 1, 0], [0, 0

In [ ]:
print(metrics.f1_score(y_true,y_pred, average='micro'))
print(metrics.accuracy_score(y_true,y_pred))
print(metrics.precision_score(y_true,y_pred, average='micro'))
print(metrics.recall_score(y_true,y_pred, average='micro'))
print(metrics.hamming_loss(y_true,y_pred))

0.8927019982623805
0.8927019982623805
0.8927019982623805
0.8927019982623805
0.10729800173761946


In [ ]:
print(x_df_test)
print(y_pred_labels)
lists = [x_df_test, y_pred_labels]
df_x = pd.concat([pd.Series(x) for x in lists], axis=1)
#print(df_x)
'''df_final = pd.DataFrame()
for x in x_df_test:
  for y in y_pred_labels:

    dict = {'Content' : x, 'App_Usage' : y[0], 'Inclusiveness' : y[1], 'User_Reaction': y[2], 'Non_human_centric': y[3]}
    df_dictionary = pd.DataFrame([dict])
    df_final = pd.concat([df_final, df_dictionary], ignore_index=True)'''

df_x.to_excel("/content/dataset-issues-output.xlsx", index=False)

['', 'sorry i didn t see the topic like social impact u fairness and misinformation but i saw this topic in your course thank you', '', 'adding albef to multimodal pre training', '', '', 'learning with noisy correspondence for cross modal matching neurips', '', '', 'add new multimodal work accepted by ijcai', '', '', 'add a paper to the category of analysis of multimodal models', 'add one paper under vqa r n add one workshop', 'hey pliang r n i ve updated the url to the recent jair published version', 'hi r nhow do you access the courses mentioned any online courses on multimodal ml', 'nan', 'thank you for your contribution to multimodal research', 'nan', 'nan', 'hi r n r nthis is a preprint recently published by researchers at fair transformer is all you need multimodal multitask learning with a unified transformer https arxiv org abs r n r nadditionally i was wondering about adding paper summaries for these papers in the list so it is easier to use for everyone else a summary readme 

In [ ]:

import os
print( os.getcwd() )
print( os.listdir() )

from google.colab import files
files.download( model_path ) 

/content
['.config', 'dataset-IssueComments.xlsx', 'data_exploration_issues_all_copy.xlsx', 'lightning_logs', 'dataset-issues-output.xlsx', 'sample_data']


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>